### ISSUE TITLE
Nick Coloring

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD151#56] opened 2018-07-26 20:37 UTC
Can someone give me a quick rundown, of how username coloring works in IntegraMOD?
It doesn't seem to be integrated with e.g. the chatbox.

Are we able to customize it?

**Comment by vendethiel** [comment] 2018-08-08 12:33
It seems like there's no way to change that, I'm really surprised.

The one I used was RCS (Rank Color System) but it's obviously woefully inadequate with PCP...

**Comment by MWE001** [comment] 2018-11-24 09:39
Nice! That works. I'm almost thinking Teelk's advanced group color mod originally took care of that. Nice fix!

**Comment by vendethiel** [comment] 2018-11-26 16:36
Well, ultimately I need to pick a mod to add group colors. I think it's a feature people really expect to have. Do you have a link to Teelk's?

**Comment by MWE001** [comment] 2018-11-27 05:45
Teelk's mod added colors to everything everywhere in every fashion. It was very at length and took a very long time to install. It was always the very first thing to ever get installed on IM 1,4,1 for a very good reason. 

I formatted the wrong hard drive a few weeks back and lost every single phpBB file ever released from 3 weeks ago until the beginning of it's existence. I did data recovery but it is sketchy what I got in return. I will start digging in the files and see if that is one of them and if so if it is even a viable file anymore. I learned the hard way just because files are recovered does not always mean they are usable.

**Comment by IntegraMOD** [comment] 2018-11-27 23:17
I uploaded the files I have on integramod.com

**Comment by IntegraMOD** [comment] 2018-11-27 23:21
I have every file ever uploaded to integramod. The only problem is that depending on what version of pafiledb was running on what version of php, some are saved as the filename and some are saved as a hash

**Comment by MWE001** [comment] 2018-11-28 00:05
Nice! I was actually getting ready to jump on and have a look for the AGCM as well. I just walked in the door from a very long day of cardiologists and all that grown up crap. Fun times. I would rather pull out my hair trying to fix 15 year old code that was made for php 3 lmao!!

**Comment by MWE001** [comment] 2018-11-28 00:14
I found it:

##############################################################
## MOD Title: Advanced Group Color Management for IntegraMOD 1.4.1
## MOD Author: Phantomk < phantomk@modmybb.com > (n/a) http://www.modmybb.com/
## IM Porter:  Teelk < nerfherder20@hotmail.com > (Tim Beasley) http://www.e-tegra.com
## MOD Description: Modify's the Group system to add colors.
## MOD Version: 1.2.5

The file is in good shape. I even have the pre mod files as well.

**Comment by vendethiel** [comment] 2018-11-28 08:58
I feel like such a mod so important (you even said it was the 1st mod people usually installed) should be included in IM. Do you agree?

**Comment by MWE001** [comment] 2018-11-28 10:46
Well, yes it probably should be. However, if I had to hazard a guess, I would say since the mod was not ported until after 1.4.1 was released that is the reason it was not included. Now I have had many beers and sleep since them days and I could very well be wrong but I am almost certain I am probably heading down correct avenue. 

Helter uploaded all of his files and I am going to upload the one that was released as officially as well that contains the 1.4.1 pre-mod files as well. I will get a link to you here in a few minutes before I head out to yet another physicians visit.

**Comment by vendethiel** [comment] 2018-11-28 12:50
I have both the versions, I'm comparing 309 and 379 ATM.
From what I see we want the 379, maybe those are SVN revision numbers.
One mentions Integra2 and the other fisubice.
Other than that, 379 just seems to add color to more places.

**Comment by vendethiel** [comment] 2018-11-29 22:13
@MWE001 Your file seems to be the same as 379.

I have implemented the mod!
I also added it in places it wasn't at before, like the shoutbox:
![image](https://user-images.githubusercontent.com/199499/49255439-4f3df900-f42c-11e8-9872-d80e676f313e.png)

**Comment by MWE001** [comment] 2018-11-30 00:13
Nice! That's cool man. I like it.

**Comment by vendethiel** [comment] 2018-11-30 01:02
I think I will replace its color picker however. I think it is pretty ugly and it could use a much better one, like you see nowadays.

**Comment by MWE001** [comment] 2018-11-30 01:30
Hey, is this very version you are working on the very version I can clone and open with my Git desktop or are you working on a local version? I ask because I have Integra installed and running perfectly fine on a Linux box and hate like hell to test and test and test only to find out I am 25 versions behind what you are building. lol Right off the bat my brain started going crazy finding things that needed fixed and my first thought was to see what version you are on. I did a sync from my desktop app with the master branch and it did not update. Now me being a newbie to Git still, is it syncing with my fork master branch or this very Integramod master Branch? I'm willing to say I made a rookie mistake and can answer my own question lol

**Comment by MWE001** [comment] 2018-11-30 01:31
Nope, I was right. It is this one I am fetching. It is showing no file changes at all. 

Want me to hold up on my testing and messing about?

**Comment by vendethiel** [comment] 2018-11-30 01:41
Hehe, I ‘m still gonna need to close off that other issue before I push.
Also I have in this same repo my ADR branch.

**Comment by MWE001** [comment] 2018-11-30 01:44
Ok that's cool no worries. I was just not wanting to spend a bunch of time on something and it be a Pull or two behind. I suddenly have some time on my hands thanks to another health issue. Doctors orders to sit on my duff.

**Comment by vendethiel** [comment] 2018-12-05 09:40
I'm fixing the last of it. Funnily enough my own system prepared groundwork for me to know where to fix things, even if I'm removing it now.

**Comment by vendethiel** [comment] 2018-12-05 12:33
There are many uses of `get_user_level_class` that AGCM doesn't replace.. yet?

I feel like it should, but I need to see pages where the coloring is wrong to make sure.

**Comment by MWE001** [comment] 2018-12-05 12:38
I just got my site reinstalled and working properly (thats why you got my chmod.php you caught me right at a reinstall). I can run through every little place I know and test. I will create a account of every user class as well. The only one I probably couldn't do would be a donor maybe. I don't have a paypal sandbox setup.

**Comment by MWE001** [comment] 2018-12-05 12:41
I can leave my website virigin too and you can use it if you want to check pages. It isn't hurting anything sitting there. Just let me know and I can get in security and shift things around to allow for the accounts needed to test.

**Comment by vendethiel** [comment] 2018-12-05 12:52
I'm going to commit my version with AGCM soon, it has a new (fairly hairy) SQL query to run.
Not sure where I'm going to put it in the install procedure.

Here it is:

```sql
#
#--[ Alter Table ]-------------------------------------
#
ALTER TABLE phpbb_groups ADD group_weight MEDIUMINT(8) DEFAULT '0' NOT NULL;
ALTER TABLE phpbb_groups ADD group_legend SMALLINT(1) DEFAULT '0' NOT NULL;
ALTER TABLE phpbb_groups ADD group_color SMALLINT(1) DEFAULT '0' NOT NULL;


ALTER TABLE phpbb_users ADD user_group_id MEDIUMINT(8) DEFAULT 0 NOT NULL;

#
#--[ Colors Table ]-------------------------------------
#

CREATE TABLE phpbb_color (
  group_id mediumint(8) NOT NULL default '0',
  color_code varchar(6) NOT NULL default '',
  themes_id mediumint(8) NOT NULL default '0',
  hover_bold smallint(1) NOT NULL default '0',
  hover_italic smallint(1) NOT NULL default '0',
  hover_underline smallint(1) NOT NULL default '0',
  bold smallint(1) NOT NULL default '0',
  italic smallint(1) NOT NULL default '0',
  underline smallint(1) NOT NULL default '0',
  KEY group_id (group_id),
  KEY themes_id (themes_id)
);

#
#--[ Data ]---------------------------------------------
#
INSERT INTO phpbb_groups (group_type, group_name, group_description, group_moderator, group_single_user) VALUES (1, 'Group_registered', 'Group_registered_desc', 0, 1);
INSERT INTO phpbb_groups (group_type, group_name, group_description, group_moderator, group_single_user) VALUES (1, 'Group_anonymous', 'Group_anonymous_desc', 0, 1);
INSERT INTO phpbb_groups (group_type, group_name, group_description, group_moderator, group_single_user) VALUES (1, 'Group_session', 'Group_session_desc', 0, 1);

INSERT INTO phpbb_color (group_id, themes_id, color_code)
SELECT g.group_id, t.themes_id, ''
FROM phpbb_groups g, phpbb_themes t;

INSERT INTO phpbb_config (config_name , config_value) VALUES ('mod_advanced_group_color_management', '1.2.5');
INSERT INTO phpbb_config (config_name , config_value) VALUES ('group_registered', 'GROUP_REGISTERED');
INSERT INTO phpbb_config (config_name , config_value) VALUES ('group_anonymous', 'GROUP_ANONYMOUS');
INSERT INTO phpbb_config (config_name , config_value) VALUES ('group_session', 'GROUP_SESSION');
INSERT INTO phpbb_config (config_name , config_value) VALUES ('agcm_check', '0');
INSERT INTO phpbb_config (config_name , config_value) VALUES ('agcm_time', '2');
INSERT INTO phpbb_config (config_name , config_value) VALUES ('agcm_value', '1200');

UPDATE phpbb_config
  SET config_value = (SELECT group_id FROM phpbb_groups WHERE group_name = 'Group_registered')
  WHERE config_name = 'group_registered';
UPDATE phpbb_config
  SET config_value = (SELECT group_id FROM phpbb_groups WHERE group_name = 'Group_anonymous')
  WHERE config_name = 'group_anonymous';
UPDATE phpbb_config
  SET config_value = (SELECT group_id FROM phpbb_groups WHERE group_name = 'Group_session')
  WHERE config_name = 'group_session';

UPDATE phpbb_config SET config_value = (SELECT group_id FROM phpbb_groups WHERE group_name = 'Group_registered')
  WHERE config_name = 'user_group_id';
UPDATE phpbb_users SET user_group_id = (SELECT group_id FROM phpbb_groups WHERE group_name = 'Group_registered');
UPDATE phpbb_users SET user_group_id = (SELECT group_id FROM phpbb_groups WHERE group_name = 'Group_anonymous')
  WHERE user_id = -1;
```

**Comment by vendethiel** [comment] 2018-12-05 12:55
To be clear: I have **not yet** tested installing the whole IM with AGCM.

But this sql I just posted installs it if you already have an IM board running.

**Comment by vendethiel** [comment] 2018-12-05 14:24
Just pushed, see if you can find bugs or places where it doesn't work.

**Comment by MWE001** [comment] 2018-12-05 14:37
Ok. I'll have to see what I can do. I am fresh out of room on my live server and due to the database issues can not get it to run on my local  host server. I'll give it a try one way or the other today.

**Comment by MWE001** [comment] 2018-12-05 17:36
Ok I'm uploading this commit right as I speak. Same server specs as I posted a few days ago over at Integra website.

**Comment by MWE001** [comment] 2018-12-05 18:04
Uploaded all files, ran chomod and double checked all permissions and ran the install. On initial run, it ran fine. It showed me all tables were installed in the database and as usual, asked me to remove the install directory before preceding to install Prill. So I did. Once I removed the install directory and clicked Install Prill, it redirected me to login.php and then give me a 500 internal server error and said my server couldn't handle that request. 

So, I visited a few other websites on the server and all were delivering pages and login forms via SSL and unprotected just fine. 

Tried a second install with this commit, same thing once again.

**Comment by MWE001** [comment] 2018-12-05 18:42
Tried leaving install file in and moving on knowing it was going to not work and it didn't work. It will not go past delete the install file. And there is no logging in at all. Message die error happens. Incomplete install.

**Comment by vendethiel** [comment] 2018-12-05 19:18
Are you running PHP 7.2? or Mysql higher than 5.4?

**Comment by MWE001** [comment] 2018-12-05 19:30
Yeah confirmed. That is all they will let me go. I can change php but sql will not allow me to change at all.

**Comment by vendethiel** [comment] 2018-12-05 19:38
I have a patch where I have started to fix all SQL errors, have them work on more recent MySQL. Now that I've reinstalled MAMP with new versions of PHP & MySQL, I'll try to get a better version by next week.
That probably means it won't work on ye olde versions but I'm fine with that.

**Comment by MWE001** [comment] 2018-12-05 19:45
I think unless someone has dedicated server they are being force fed newer stuff anyhow due to insecure scripts. So it might not be a big deal anyhow.

**Comment by vendethiel** [comment] 2018-12-14 16:33
OK, I just installed it on my windows server.
Only issue I had is that the install procedure took too long. I changed install's php time limit to 2minutes instead of 30 seconds and then it worked.
Now I can confirm that AGCM works out of the box -- but I did the test on PHP5.5; the one I have installed here.

I'm going to close this issue. If someone finds an issue on PHP7+, please reopen and I'll fix it.

**Comment by vendethiel** [comment] 2018-12-21 16:21
Seems like new users don't get automatically the "Registered User" color :(.

**Closed** 2018-12-21 16:41 UTC
Labels: enhancement

**Comment by vendethiel** [comment] 2018-12-21 16:44
Sorry, PCP, I win this time :).
